version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: instalar_dependencias.sh
      timeout: 300
      runas: root
    - location: arrancar_servidor.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: parar_servidor.sh
      timeout: 300
      runas: root

